# Generated by Django 3.0.4 on 2020-07-11 13:34

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='latitude',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='longitude',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
