# Generated by Django 3.0.4 on 2020-07-11 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200711_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='latitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='animal',
            name='longitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
