# Generated by Django 3.0.4 on 2020-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200715_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=2000)),
            ],
        ),
    ]
