# Generated by Django 3.0.4 on 2020-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_report_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='task_description',
            name='image',
            field=models.BinaryField(),
        ),
    ]
