# Generated by Django 3.0.4 on 2020-07-11 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_researcher_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='animal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[''], size=None),
            preserve_default=False,
        ),
    ]
